### ISSUE TITLE
Add new column: streetNumber

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#27]
streetNumber column should be created from street address field. While streetNumber will be used for validating address, it does not need to be returned when there is a voter match.

**Comment by cwisdo** [comment]
Not sure how "created from" will work?  

I think this means we're splitting `streetAddress` into  `streetNumber` and potentially(?) `streetName` ?

For the validation, confirming that the `streetNumber`  (and `streetName`) will be new lookup parameters for `lookupVoterByAddress` and both will be required for match?

**Comment by awoflaherty** [comment]
streetNumber not streetName will used for LookUpVoterByAddress API
full address should be returned so it can be used in Confirm Identity screen in app.
I am OK if back end returns both streetNumber and streetAddress
