### ISSUE TITLE
Change lookupVoterByAddress API

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#29]
change the lookupAddress API to accept and match using firstName, lastName, yearOfBirth, zip5 and streetNumber.
For columns firstName, lastName, and streetNumber, characters are case insensitive.

**Comment by awoflaherty** [comment]
Real life example: https://ballottrace.org/home

**Comment by cwisdo** [comment]
Confirming that we are altering this specification as follows:

- **removing**:  state, city  
- **adding**: streetNumber and firstname

**Comment by awoflaherty** [comment]
Yes, removing those fields from the API call to the back end.
These fields will remain in the return response to the app.

Thank you and Happy Thanksgiving

**Comment by awoflaherty** [comment]
Confirming that V1.4 deployment still has City and State as required fields.  Revised wireframes only have street number and zip code, so these should be removed.

**Comment by cwisdo** [comment]
I'm not seeing these as required fields.

curl --header "Content-Type: application/json" -request POST --data '{"firstName": "Rowan","lastName": "Quinn","yearOfBirth": "2000","streetNumber": "3","ZIP5": "77707"}' https://9zdmvlvyu7.execute-api.us-east-1.amazonaws.com/development-v1-4-0/lookupVoterByAddress

**Comment by awoflaherty** [comment]
Works as requested.
