### ISSUE TITLE
Add a new column: dateOfBirth

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#30]
Keep YOB column and add dateofBirth to the database.  Return dateOfBirth in place of YOB.

**Comment by cwisdo** [comment]
By "in place of" you mean, we should *keep* yearOfBirth as the search attribute in all of the lookup queries where it is used, but return "dateOfBirth" in the voter data record (by "in place of" do you want to suppress returning yearOfBirth in returned voter record, or is it okay to return both?)

**Comment by awoflaherty** [comment]
keep YOB as the search attribute in all of the look up queries.
return at minimum DOB and I am fine if YOB is also returned.
