### ISSUE TITLE
Add new API: getTestPrintPage

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#31]
getTestPrintPage: Used to pull a URL to use to get a PDF file that is the test page a voter will print to confirm their printer is set up for the app. The test page is common for all voters during a given election.

Inputs: none

Errors: 400 no match, if there is no current election. 

Outputs: 
JSON: {“testPrintPageURL”: Url}

**Comment by awoflaherty** [comment]
I will create a PDF shortly and add to this issue.

**Comment by awoflaherty** [comment]
[MarkitTestPrintPage.pdf](https://github.com/TrustTheVote-Project/ABC-backend/files/7590614/MarkitTestPrintPage.pdf)

Use this PDF for now.

**Comment by cwisdo** [comment]
If the test print page changes per election, then `testPrintPageURL` should be an attribute of the election object?

**Comment by awoflaherty** [comment]
> If the test print page changes per election, then `testPrintPageURL` should be an attribute of the election object?

Yes, should I ask John if this should be a line item in getElection API rather than its own API?

**Comment by awoflaherty** [comment]
I spoke to John. He wants it to be a stand alone call. At deployment time, the affidavit template file and the test page file would need to get deployed with the software as an instance specific asset.

**Comment by cwisdo** [comment]
Sorry, I didn't follow up immediately.  

- Yes, it needs to be a standalone call in any case because the URL is a S3 pre-signed URLs for temporary object access
- The filename itself *also* needs to be an attribute of the election object (so that it can be set and configured in the administrative backend) but this isn't a client concern, so we can make this an "admin only" attribute.

**Comment by awoflaherty** [comment]
Should I close this issue?
Did you document that the  filename itself needed to be an attribute of the election object as an "admin only" attribute?

**Comment by awoflaherty** [comment]
@cwisdo I spoke with John on Jan 25th and he is re-thinking this new API.  Likely to be deprecated in the next version.  Instead we will store a base 64 string test page in the app.
