### ISSUE TITLE
revise affidavit template

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/ABC-backend#39]
Requirements:

The form must have a field for every field the front-end app collects.
There should be a second page with a field for a photo id
There should be a field for name of witness (single field)
There should be a field for address of witness, but no field labels are needed

**Comment by awoflaherty** [comment]
@cwulfman - Can this be closed?

**Comment by cwulfman** [comment]
As I recall, I gave you a draft affidavit to review but we've never reconnected on it.  If you no longer need this, by all means close it.

**Comment by awoflaherty** [comment]
John, @trustthevote 
Are the 4 sample affidavits Cliff provided enough or do we need to test a sample affidavit with witness address?
The Alaska one is the most complex Tusk provided.
https://github.com/cwulfman/MarkIt-affidavit-gallery/blob/main/AlaskaAffidavit.pdf

**Comment by awoflaherty** [comment]
@cwulfman - I don't have permission to close it.  Either you or @cwisdo should do that.
