### ISSUE TITLE
document ballot affidavit fields

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/ABC-backend#40]
To address #39 (and probably for other purposes), the implementer needs a complete list of the fields that are presented in the voting app.

**Comment by cwulfman** [comment]
Anne O'Flaherty provided this table:

Field | Type |
| --- | ---- |
VIDN | string |
firstName | string |
lastName | string |
streetAddress | string |
addressLine2 | string |
city | string |
stateCode | string |
ZIP5 | string |
DLN | string |
stateIDN | string |
dateOfBirth | string |
SSN | string |
email | string |
mobilePhone | string |
eligibleAbsentee | boolean |
disabilityAbsentee | boolean |
UOCAVAAbsentee | boolean |
DLPhotoRequired | boolean |
electionJurisdiction | string |
precinctID | int |
partyAffiliation | string |
ballotID | int |
completedN | int |
incompletedN | int |
completeTimeStamp | string |
incompletedTimeStamp | string |

**Comment by awoflaherty** [comment]
@cwulfman OK to close?
