### ISSUE TITLE
getConfigurations request: Add minYearOfBirth

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#41]
I am not sure what is a good label.  It will be used to set the Year of Birth data entry minimum value.  If a county  allows a person to vote at 16, then the app's minimum accepted value would be 2006 (2022-16).  If a county's minimum age is 18, then the app's minimum accepted value would be 2004

**Comment by cwisdo** [comment]
minYearOfBirth is just a rough estimate though, right? And potentially wrong a good portion of the time.

Oughtn't the real specification just be **voting age** and the criteria "will be voting age by date of election"  

If we do this, we can calculate an exact minimum date of birth.

**Comment by awoflaherty** [comment]
If this were a registration app, then yes, we would be asking for the person's exact DOB and calculating if they were eligible to register.

This app is for voters who have completed their registration and now want to vote absentee.  In this app, we do not ask for their exact DOB.  Instead the request is for their Year of Birth and want to calculate YOB minimum values based on this getConfigurations value.

This was something John Sebes wanted, so we can review this request with him too.
