### ISSUE TITLE
getConfigurations URL corrections

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#46]
There are 3 incorrect links listed in getConfigurations and 1 to be removed

       "checkYourBallotLink": "https://astro-miniweb.s3.amazonaws.com/check-your-ballot.html",
should be https://astro-miniweb.s3.amazonaws.com/about-ballot-checking.html

        "aboutTrackingYourBallotLink": "https://astro-miniweb.s3.amazonaws.com/about-tracking-your-ballot.html",
should be https://astro-miniweb.s3.amazonaws.com/digital-ballot-checking.html

        "trackYourBallotLink": "https://astro-miniweb.s3.amazonaws.com/track-your-ballot.html",
remove

        "ballotPairingErrorLink": "https://astro-miniweb.s3.amazonaws.com/ballot-pairing-error.html"
should be https://astro-miniweb.s3.amazonaws.com/digital-ballot-pairing-error.html

**Comment by ahmadjubair33** [comment]
Hi @awoflaherty Can I FIx this issue?
Can you please tell me in which branch changes are required? Thank You

**Comment by awoflaherty** [comment]
I am not sure which branch either - probably february-2022-updates.  I recommend you talk with Chris re: this.  Also, I don't know if this will be a hot fix to v3-0-1 API or will be a new revision.

@cwisdo, Anything else to add?

**Comment by cwisdo** [comment]
We can upload the config change anytime.  It's data not code.  

These were copied from the specification document (and I just checked, it reflects the same).

@ahmadjubair33  Yes, I think the best way to do this is to use the code in GitHub control. Quick and easy: if you want to edit the file and send back to be, I'll upload.

- https://github.com/TrustTheVote-Project/ABC-backend/blob/february-2022-updates/db-json/set-electionconfigs-example.json

If you want to over process it, you can:

- Pull the feb-2022 branch (https://github.com/TrustTheVote-Project/ABC-backend/tree/february-2022-updates)
- Branch from that
- Edit the set election configs example (https://github.com/TrustTheVote-Project/ABC-backend/blob/february-2022-updates/db-json/set-electionconfigs-example.json) to be exactly what you want
- And then do a PR  back to the feb-2022 branch, I'll accept and then set the config update with the admin function

**Comment by awoflaherty** [comment]
I made the changes and forked because I didn't have access to branch.  Let me know if this is ok

**Comment by awoflaherty** [comment]
I have one more URL change to make.  Would you like @ahmadjubair33  or me to do it?
in getConfigurations
Current
 “aboutTrackingYourBallotLink": "https://astro-miniweb.s3.amazonaws.com/about-tracking-your-ballot.html"

Needs to  be changed to
aboutTrackingYourBallotLink": "https://astro-miniweb.s3.amazonaws.com/digital-ballot-checking.html”

**Comment by awoflaherty** [comment]
All URLs are correct.
