### ISSUE TITLE
admin-ui throws Network Error at startup

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/ABC-backend#51]
`yarn next dev -p 3001`

produces this in the browser window:

```
Unhandled Runtime Error

Error: Network Error
Call Stack
createError
node_modules/axios/lib/core/createError.js (16:0)
handleError
node_modules/axios/lib/adapters/xhr.js (117:0)
```

tested on Firefox 100.0 and Safari
<img width="1344" alt="Screen Shot 2022-05-12 at 2 13 06 PM" src="https://user-images.githubusercontent.com/891097/168141571-ac0e7fc4-e8d9-4718-814d-84fcdedb1b50.png">

console shows multiple "DataCloneError: The object could not be cloned." errors.

**Comment by awoflaherty** [comment]
@cwulfman - Can this be closed?

**Comment by awoflaherty** [comment]
@trustthevote and @cwisdo 
Would you comment on this item? Thanks

**Comment by cwisdo** [comment]
Hi @cwulfman @awoflaherty :  

By default the admin api accesses the local version of Provisioner (at localhost:3000)

So, first question, if accessing the local version of Provisioner, did you start the local version, and initialize the database, etc.

There should be documentation for this in the main Readme file.

If instead you're accessing a remote version of the Provisioner, which main endpoint were you accessing?

**Comment by trustthevote** [comment]
OTBE

**Comment by trustthevote** [comment]
OTBE
