### ISSUE TITLE
Revise getConfigurations

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/ABC-backend#54]
Current:
  "affidavitOfferSignatureViaPhoto": true,
  "affidavitOfferSignatureViaName": true,

Change to 
  "affidavitOfferSignatureViaPhoto": false,
  "affidavitOfferSignatureViaName": false,

**Comment by cwisdo** [comment]
@awoflaherty This was a data update: done/ and now configurable by the App team with the script I provided via private functions. 

Can we close?
